### ISSUE TITLE
article 008 hs

### ISSUE THREAD

**Issue by spham** [capsulescodes/articles#1]
`composer require capsulescodes/package
`
In PackageDiscoveryTrait.php line 368:
                                                                              
  Could not find a matching version of package capsulescodes/package. Check   
  the package spelling, your version constraint and that the package is avai  
  lable in a stability which matches your minimum-stability (stable).         
                                                                              

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

**Comment by mho22** [comment]
@spham I followed the steps in the `articles/README.md` file and `008-create-a-laravel-package-on-your-local-environment/README.md` file and it worked. 

Where do you run `composer require capsulescodes/package` ?


Do you have this line in your `template/composer.json` :

```
"repositories": [ { "type": "path", "url": "../package" } ]
```

And this line in the `package/composer.json` : 

```
"name": "capsulescodes/package",
```

And ultimately, do you have your `package`folder respecting the `"url": "../package"` path ?

Is it possibly an error from the article itself ?

**Comment by mho22** [comment]
@spham I followed the steps, reread the article, and everything worked fine. Feel free to reopen the issue if you encounter the same problems again.
